// src/components/ui/GooeyInput.svelte
<script lang="ts">
  import { Spring } from "svelte/motion";
  import { crossfade } from "svelte/transition";
  import { cubicOut } from "svelte/easing";
  import { cn } from "@/lib/utils";

  interface Props {
    placeholder?: string;
    class?: string;
    /** Collapsed control width in px */
    collapsedWidth?: number;
    /** Expanded control width in px */
    expandedWidth?: number;
    /** Horizontal offset when expanded (px), aligns detached bubble */
    expandedOffset?: number;
    /** Gaussian blur amount for the gooey SVG filter */
    gooeyBlur?: number;
    value?: string;
    disabled?: boolean;
    onOpenChange?: (open: boolean) => void;
  }

  let {
    placeholder = "Type to search...",
    class: className,
    collapsedWidth = 155,
    expandedWidth = 375,
    expandedOffset = 50,
    gooeyBlur = 6,
    value = $bindable(""),
    disabled = false,
    onOpenChange,
  }: Props = $props();

  // $props.id() must be a bare top-level initializer, so sanitising for use in
  // an SVG id and a url(#…) reference happens in a second step.
  const uid = $props.id();
  const filterId = `gooey-filter-${uid.replace(/[^a-zA-Z0-9_-]/g, "")}`;

  let rootEl = $state<HTMLDivElement | null>(null);
  let inputEl = $state<HTMLInputElement | null>(null);
  let isExpanded = $state(false);
  let availableWidth = $state<number | null>(null);

  /**
   * The React original drove these with motion's spring (stiffness 400,
   * damping 28, mass 1 — damping ratio ~0.7, so a fast move with a touch of
   * overshoot). Svelte's Spring uses its own normalised parameters rather than
   * physical units, so these are re-tuned to that response rather than copied.
   */
  const SPRING = { stiffness: 0.2, damping: 0.62 };

  const effectiveExpandedWidth = $derived(
    availableWidth != null
      ? Math.min(expandedWidth, availableWidth - expandedOffset)
      : expandedWidth,
  );

  // svelte-ignore state_referenced_locally
  // Intentional: this is only the spring's starting position. The $effect below
  // owns the target from the first run onward.
  const rowWidth = new Spring(collapsedWidth, SPRING);
  const rowMarginLeft = new Spring(0, SPRING);
  const bubbleScale = new Spring(0, SPRING);
  const bubbleOpacity = new Spring(0, SPRING);
  const bubbleX = new Spring(0, SPRING);

  $effect(() => {
    rowWidth.target = isExpanded ? effectiveExpandedWidth : collapsedWidth;
    rowMarginLeft.target = isExpanded ? expandedOffset : 0;
    bubbleScale.target = isExpanded ? 1 : 0;
    bubbleOpacity.target = isExpanded ? 1 : 0;
    bubbleX.target = isExpanded ? -10 : 0;
  });

  // Track the parent's width so the expanded control never overflows it.
  $effect(() => {
    const parent = rootEl?.parentElement;
    if (!parent) return;
    const measure = () =>
      (availableWidth = parent.getBoundingClientRect().width);
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(parent);
    return () => observer.disconnect();
  });

  // Focus on expand; clear the query on collapse. Guarded on the previous state
  // so the initial render cannot clobber a value passed in by the parent.
  let wasExpanded = false;
  $effect(() => {
    if (isExpanded) {
      inputEl?.focus();
    } else if (wasExpanded) {
      value = "";
    }
    wasExpanded = isExpanded;
  });

  function setExpanded(next: boolean) {
    isExpanded = next;
    onOpenChange?.(next);
  }

  function handleExpand() {
    if (!disabled) setExpanded(true);
  }

  function handleBlur() {
    if (!value) setExpanded(false);
  }

  /**
   * Svelte's equivalent of motion's `layoutId`: the icon is FLIP-morphed between
   * its position inside the pill and its position in the detached bubble, which
   * is what sells the gooey split.
   */
  const [send, receive] = crossfade({ duration: 350, easing: cubicOut });

  const surfaceClass =
    "bg-foreground text-background shadow-sm ring-1 ring-border/60";
</script>

{#snippet searchIcon()}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="2"
    class="size-4 shrink-0"
  >
    <circle cx="11" cy="11" r="8" />
    <path d="m21 21-4.3-4.3" />
  </svg>
{/snippet}

<div
  bind:this={rootEl}
  class={cn("relative flex items-center justify-center", className)}
>
  <svg class="absolute hidden h-0 w-0" aria-hidden="true">
    <defs>
      <filter id={filterId} x="-50%" y="-50%" width="200%" height="200%">
        <feGaussianBlur in="SourceGraphic" stdDeviation={gooeyBlur} result="blur" />
        <feColorMatrix
          in="blur"
          type="matrix"
          values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10"
          result="goo"
        />
        <feComposite in="SourceGraphic" in2="goo" operator="atop" />
      </filter>
    </defs>
  </svg>

  <div
    class="relative flex h-10 items-center justify-center"
    style="filter: url(#{filterId})"
  >
    <div
      class="flex h-10 items-center justify-center"
      style="width: {rowWidth.current}px; margin-left: {rowMarginLeft.current}px"
    >
      <button
        type="button"
        {disabled}
        onclick={handleExpand}
        class={cn(
          "flex h-10 w-full cursor-pointer items-center justify-center gap-2 rounded-full px-4 text-sm font-medium outline-none transition-[color,box-shadow] focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50",
          surfaceClass,
        )}
      >
        {#if !isExpanded}
          <span in:receive={{ key: filterId }} out:send={{ key: filterId }}>
            {@render searchIcon()}
          </span>
        {/if}
        <input
          bind:this={inputEl}
          bind:value
          type="search"
          enterkeyhint="search"
          autocomplete="off"
          onblur={handleBlur}
          disabled={disabled || !isExpanded}
          {placeholder}
          class={cn(
            "h-full min-w-0 flex-1 bg-transparent text-sm text-background outline-none",
            isExpanded
              ? "placeholder:text-background/50 dark:placeholder:text-background/45"
              : "pointer-events-none placeholder:text-background/80 dark:placeholder:text-background/70",
          )}
        />
      </button>
    </div>

    <div
      class="absolute top-1/2 left-0 flex size-10 items-center justify-center"
      style="opacity: {bubbleOpacity.current}; transform: translateY(-50%) translateX({bubbleX.current}px) scale({bubbleScale.current})"
    >
      <div
        class={cn(
          "flex size-10 items-center justify-center rounded-full",
          surfaceClass,
        )}
      >
        {#if isExpanded}
          <span in:receive={{ key: filterId }} out:send={{ key: filterId }}>
            {@render searchIcon()}
          </span>
        {/if}
      </div>
    </div>
  </div>
</div>

// src/components/ui/gooey-input.tsx
"use client";

import {
  useState,
  useRef,
  useEffect,
  useId,
  useMemo,
  useCallback,
  type ChangeEvent,
} from "react";
import { motion } from "motion/react";
import { cn } from "@/lib/utils";

function GooeyFilter({
  filterId,
  blur,
}: {
  filterId: string;
  blur: number;
}) {
  return (
    <svg className="absolute hidden h-0 w-0" aria-hidden>
      <defs>
        <filter id={filterId} x="-50%" y="-50%" width="200%" height="200%">
          <feGaussianBlur in="SourceGraphic" stdDeviation={blur} result="blur" />
          <feColorMatrix
            in="blur"
            type="matrix"
            values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10"
            result="goo"
          />
          <feComposite in="SourceGraphic" in2="goo" operator="atop" />
        </filter>
      </defs>
    </svg>
  );
}

function SearchIcon({ layoutId }: { layoutId: string }) {
  return (
    <motion.svg
      layoutId={layoutId}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      className="size-4 shrink-0"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </motion.svg>
  );
}

const transition = {
  type: "spring" as const,
  stiffness: 400,
  damping: 28,
  mass: 1,
};

const iconBubbleVariants = {
  collapsed: { scale: 0, opacity: 0, x: 0 },
  expanded: { scale: 1, opacity: 1, x: -10 },
};

export interface GooeyInputClassNames {
  root?: string;
  filterWrap?: string;
  buttonRow?: string;
  trigger?: string;
  input?: string;
  bubble?: string;
  bubbleSurface?: string;
}

export interface GooeyInputProps {
  placeholder?: string;
  className?: string;
  classNames?: GooeyInputClassNames;
  /** Collapsed control width in px */
  collapsedWidth?: number;
  /** Expanded control width in px */
  expandedWidth?: number;
  /** Horizontal offset when expanded (px), aligns detached bubble */
  expandedOffset?: number;
  /** Gaussian blur amount for the gooey SVG filter */
  gooeyBlur?: number;
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
}

export function GooeyInput({
  placeholder = "Type to search...",
  className,
  classNames,
  collapsedWidth = 155,
  expandedWidth = 375,
  expandedOffset = 50,
  gooeyBlur = 6,
  value: valueProp,
  defaultValue = "",
  onValueChange,
  onOpenChange,
  disabled = false,
}: GooeyInputProps) {
  const reactId = useId();
  const safeId = reactId.replace(/:/g, "");
  const filterId = `gooey-filter-${safeId}`;
  const iconLayoutId = `gooey-input-icon-${safeId}`;
  const inputLayoutId = `gooey-input-field-${safeId}`;

  const rootRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const prevExpandedRef = useRef(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const [availableWidth, setAvailableWidth] = useState<number | null>(null);

  useEffect(() => {
    if (!rootRef.current) return;
    const measure = () => {
      const parent = rootRef.current?.parentElement;
      if (parent) setAvailableWidth(parent.getBoundingClientRect().width);
    };
    measure();
    const obs = new ResizeObserver(measure);
    if (rootRef.current.parentElement) obs.observe(rootRef.current.parentElement);
    return () => obs.disconnect();
  }, []);
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);

  const isControlled = valueProp !== undefined;
  const searchText = isControlled ? valueProp : uncontrolledValue;

  const setSearchText = useCallback(
    (next: string) => {
      if (!isControlled) {
        setUncontrolledValue(next);
      }
      onValueChange?.(next);
    },
    [isControlled, onValueChange],
  );

  const setExpanded = useCallback(
    (next: boolean) => {
      setIsExpanded(next);
      onOpenChange?.(next);
    },
    [onOpenChange],
  );

  useEffect(() => {
    if (isExpanded) {
      inputRef.current?.focus();
    } else if (prevExpandedRef.current) {
      setSearchText("");
    }
    prevExpandedRef.current = isExpanded;
  }, [isExpanded, setSearchText]);

  const effectiveExpandedWidth = availableWidth != null
    ? Math.min(expandedWidth, availableWidth - expandedOffset)
    : expandedWidth;
  const effectiveOffset = expandedOffset;

  const buttonVariants = useMemo(
    () => ({
      collapsed: { width: collapsedWidth, marginLeft: 0 },
      expanded: { width: effectiveExpandedWidth, marginLeft: effectiveOffset },
    }),
    [collapsedWidth, effectiveExpandedWidth, effectiveOffset],
  );

  const handleExpand = useCallback(() => {
    if (!disabled) setExpanded(true);
  }, [disabled, setExpanded]);

  const handleChange = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => {
      setSearchText(e.target.value);
    },
    [setSearchText],
  );

  const handleBlur = useCallback(() => {
    if (!searchText) setExpanded(false);
  }, [searchText, setExpanded]);

  const surfaceClass =
    "bg-foreground text-background shadow-sm ring-1 ring-border/60";

  return (
    <div
      ref={rootRef}
      className={cn(
        "relative flex items-center justify-center",
        className,
        classNames?.root,
      )}
    >
      <GooeyFilter filterId={filterId} blur={gooeyBlur} />

      <div
        className={cn(
          "relative flex h-10 items-center justify-center",
          classNames?.filterWrap,
        )}
        style={{ filter: `url(#${filterId})` }}
      >
        <motion.div
          className={cn("flex h-10 items-center justify-center", classNames?.buttonRow)}
          variants={buttonVariants}
          initial="collapsed"
          animate={isExpanded ? "expanded" : "collapsed"}
          transition={transition}
        >
          <button
            type="button"
            disabled={disabled}
            onClick={handleExpand}
            className={cn(
              "flex h-10 w-full cursor-pointer items-center justify-center gap-2 rounded-full px-4 text-sm font-medium outline-none transition-[color,box-shadow] focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50",
              surfaceClass,
              classNames?.trigger,
            )}
          >
            {!isExpanded ? (
              <SearchIcon layoutId={iconLayoutId} />
            ) : null}
            <motion.input
              layoutId={inputLayoutId}
              transition={transition}
              ref={inputRef}
              type="search"
              enterKeyHint="search"
              autoComplete="off"
              value={searchText}
              onChange={handleChange}
              onBlur={handleBlur}
              disabled={disabled || !isExpanded}
              placeholder={placeholder}
              className={cn(
                "h-full min-w-0 flex-1 bg-transparent text-sm text-background outline-none",
                isExpanded
                  ? "placeholder:text-background/50 dark:placeholder:text-background/45"
                  : "pointer-events-none placeholder:text-background/80 dark:placeholder:text-background/70",
                classNames?.input,
              )}
            />
          </button>
        </motion.div>

        <motion.div
          className={cn(
            "absolute top-1/2 left-0 flex size-10 -translate-y-1/2 items-center justify-center",
            classNames?.bubble,
          )}
          variants={iconBubbleVariants}
          initial="collapsed"
          animate={isExpanded ? "expanded" : "collapsed"}
          transition={transition}
        >
          <div
            className={cn(
              "flex size-10 items-center justify-center rounded-full",
              surfaceClass,
              classNames?.bubbleSurface,
            )}
          >
            <SearchIcon layoutId={iconLayoutId} />
          </div>
        </motion.div>
      </div>
    </div>
  );
}
